apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  completions: 10
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo","Hello World!!!"]
      restartPolicy: Never