apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:  
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["ls","/venkat"]
      restartPolicy: Never