apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:  
  #activeDeadlineSeconds: 20
  completions: 30
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo","hello World!!!!"]
      restartPolicy: Never